### ISSUE TITLE
world gen fails to complete (EntityLargeCroc)

### ISSUE THREAD

**Issue by Cat-McCatface** [m1k3s/reptiles#1]
When creating a new world (it) appears to generate successfully but stops before player is allowed to interact. Closing internal server causes mc to hardlock but not trigger crash report. Removing reptiles resolves world gen issue.

forge: 1.10-12.18.0.2000-1.10.0
reptiles: 1.10-3.5.0-50
log excerpt attached
[log.txt](https://github.com/m1k3s/reptiles/files/336261/log.txt)

**Comment by m1k3s** [comment]
fixed the attribute registry issue. This has been in the code for a while. Neither forge nor minecraft enforces this issue. This bug never fired on my system. Maybe other mods present?
