### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Sunconure11** [m1k3s/reptiles#10]
https://pastebin.com/rMdmVHx7

Possible conflict with primitive mobs, perhaps, which got updated recently for 1.12.

**Comment by PapiDimmi** [comment]
I also crashed after installing Reptile Mod.

**Crash log**: https://pastebin.com/raw/ZCNH7eF2

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**Primitive Mobs version**: 3.8.4-78

**Comment by PapiDimmi** [comment]
Fixed it version [1.1.2beta](https://minecraft.curseforge.com/projects/primitive-mobs/files/2503039). Thanks, @Vazkii!

**Comment by m1k3s** [comment]
the duplicate ID issue should not be the reptile mod. I only use the IDs generated by Forge. I'll close this as it seems to be another mod issue at this point.
