### ISSUE TITLE
Crocs spawn on beaches next to cold biomes

### ISSUE THREAD

**Issue by Ash70** [m1k3s/reptiles#11]
Beaches have a temperature of 0.8, but they generate between any biome and the ocean (and are usually very small/narrow) so crocs will wander into cold and snowy biomes. This is particularly noticeable using mods like geographicraft.
Possible solutions I can come up with:
1) Add option for minimum temperature for spawning
2) Add blacklist for excluding biomes

**Comment by m1k3s** [comment]
All cold biomes are excluded from the initial spawn biomes, i.e., blacklisted, and this covers the minimum temperature as well. So far nothing seems to work only in cold biomes, like killing or having the reptiles move back to a warm climate. I'm still working on a fix.

**Comment by m1k3s** [comment]
It's better than it was.

**Comment by EvertX** [comment]
I noticed this too and checking your code it seems crocodiles spawn in rivers and on beaches, but those can spawn at the edge of any biome, including cold ones. That is the reason they show up there. Crocodiles should check for biome temperature when spawning in rivers/on beaches to prevent this. Not sure if that is possible?

**Comment by m1k3s** [comment]
in EntityCrocBase line 111, getCanSpawnHere() I do check for the temperature. These edge biomes are hard to account for. I even had a method to check 8 blocks and all directions for colder biomes; that didn't work either. I will continue to work on this though.
