### ISSUE TITLE
Chameleon leaking OpenGL state

### ISSUE THREAD

**Issue by codetaylor** [m1k3s/reptiles#12]
First, thank you for your work on this mod!

I've noticed an issue with entities becoming transparent when they shouldn't be and I've narrowed it down to this mod, specifically the Chameleon entity.

### Steps to Reproduce

1. First, spawn a chameleon
2. Next, spawn a cow
3. Notice the cow is roughly 50% alpha
4. Next, remove the chameleon
5. Notice the cow returns to proper alpha

![2018-04-08_19 33 17](https://user-images.githubusercontent.com/1240716/38476734-392445c4-3b64-11e8-9d21-549d07c988dd.png)
![2018-04-08_19 33 48](https://user-images.githubusercontent.com/1240716/38476736-3b0b0260-3b64-11e8-8346-8347e687ca22.png)

I could be mistaken, but I believe the problem lies here: [LayerChameleonSkin.java#L46](https://github.com/m1k3s/reptiles/blob/master/reptiles/client/LayerChameleonSkin.java#L46). The layer is rendered after the model and the next model rendered, in this case the cow, doesn't reset the GL color or re-enable the alpha test before rendering.

### Versions
MC: 1.12.2
Forge: 14.23.2.2654
Reptiles: 1.12.2-3.8.4-82

**Comment by m1k3s** [comment]
Thanks for the debugging. I think I fixed it, I changed all the raw GL11 calls to GlStateManager. That seems to have stopped the state leaking. I uploaded a new reptilemod version to CurseForge. 
I'll close this for now, let me know if that doesn't fix it.
