### ISSUE TITLE
[1.10.2] Config for Reptile Sounds

### ISSUE THREAD

**Issue by praetoras** [m1k3s/reptiles#3]
I love my pet monitor, but the hissing can get loud/annoying after a while. Would it be possible to include a config option to either adjust the volume and/or disable the hissing?

**Comment by m1k3s** [comment]
I have added a config option for the talkInterval and the talkVolume. That way you can change the volume and change the interval of the ambient hissing as well. I am currently testing this new feature and should be releasing an updated version soon. Thanks for the suggestion.

**Comment by m1k3s** [comment]
build 58 is on the Curse site. config options for talk interval and volume have been added to the mod.
