### ISSUE TITLE
Lack of spawning in 1.10.2 Version

### ISSUE THREAD

**Issue by ivardensphere** [m1k3s/reptiles#4]
Hello. I've used this wonderful mod since 1.7.10 and was excited to see a 1.10.2 version.

After installing this into a fresh 1.10.2 pack and new world I noticed the reptiles were not spawning in any biomes.

I decided to test against BoP vs vanilla and with just JEI and Reptiles only, they still do not spawn in any biome. I played around with the cfg setting the max spawns to high numbers and min max reptiles high as well. I'm not sure if forge changed entity spawning or something?

The logs do show the biomes they "can spawn in" a well so I know the mod is loading, just no natural spawning is happening.

**Comment by m1k3s** [comment]
I'm not sure what is happening. the reptile mod uses vanilla spawning through Forge. I wasn't having any spawn issues in 1.10.2 that I recall. Sometimes the reptiles could be hard to find, but they did spawn. I'll try to take a look at this sometime. I'm currently working on 1.11.2.

**Comment by m1k3s** [comment]
I found a bug in the spawn code for version 1.11.2. I'm not sure when this issue started. I'm closing this issue as the fix is in 1.11.2.
