### ISSUE TITLE
Port over biome spawning changes to 1.10.2

### ISSUE THREAD

**Issue by Sunconure11** [m1k3s/reptiles#5]
While I see you are moving to 1.11, I would advise porting over the biomedictionary spawn settings to 1.10.2 as well, as that should've been included in the mod from the start. 1.11 is also still not viable for many players.

**Comment by m1k3s** [comment]
The reptile mod has been using BiomeDictionary since 1.7.10 (at least). 1.10.2 should spawning should be working fine. If you having a specific problem with spawning please create another issue, I'm closing this one.

**Comment by Sunconure11** [comment]
Ah.
