### ISSUE TITLE
Not working with forge

### ISSUE THREAD

**Issue by saraminecraft** [m1k3s/reptiles#6]
Hi! Thank you so much for the amazing mod and the fantastic work!!

 

However I am currently on MC version 1.11.2 and using Forge 1.11.2-13.20.0.2304. I was using your mod on a server and noticed there were absolutely NO reptiles spawning.

 

I thought it might be a mod conflict so I made a new single player game with NO MODS other than OptiFine_1.11.2_HD_U_B9, reptilemod-1.11.2-3.6.2-67, and journeymap-1.11.2-5.4.6 so I could at least easily find the reptiles. However other than at the original spawn location, there are still NO REPTILES SPAWNING in any biomes. I think this is an issue with Forge and your mod. Can you possibly look into this? I am not an expert enough to try and give any advice, but since I did take the time to test this issue I am 100% sure it is not a mod conflict but rather a problem with forge and Reptile Mod. I would truly appreciate the time as I really want to use your mod. 

 

Many Thanks and Regards,

Sara <3

**Comment by m1k3s** [comment]
I removed the despawn config variable. and set 'canDespawn' to false in the Entity classes. This should fix the 'nospawn' bug. Thanks for your help in finding and fixing this bug!
