### ISSUE TITLE
Suggestion: Megalania meat and leather

### ISSUE THREAD

**Issue by Sunconure11** [m1k3s/reptiles#8]
Since it still exists, just as a config option, would it be possible to give the megalania some specialized drops too?

**Comment by m1k3s** [comment]
I'm going to add megalania specific drops and probably implement making armor from the various reptiles hides. I'll close this out when that is done. thanks for the suggestion!

**Comment by Sunconure11** [comment]
Looks like this was implemented. Would it be possible to add config options to disable hides to leather or iron armor?

**Comment by m1k3s** [comment]
If I understand you correctly you want a config option to disable hides being used to make armor? I'm not sure exactly what you're asking.

**Comment by Sunconure11** [comment]
Yes, that is what I meant.

**Comment by Sunconure11** [comment]
@m1k3s While this probably deserves its own issue, but I am unable to remove the recipes for the alternate armor recipes this mod gives, using crafttweaker. It looks like you are calling for items that do not exist, looking at your recipes.

**Comment by m1k3s** [comment]
The recipes won't work if the items don't exist. I assume you are talking about the recipe json files. I'm not familiar with crafttweaker. Can you please elaborate and point to the items in the json files that don't exist.

**Comment by Sunconure11** [comment]
Briefly, it seemed it was calling for things like "megalania_helmet", but that seems to have been resolved.

**Comment by m1k3s** [comment]
I updated github, but before that the latest mod version had been posted to curseforge. Are you still having issues with crafttweaker?

**Comment by Sunconure11** [comment]
I had to work around it, by recreating the vanilla recipes for the armor sets, I'll try and see if I can recreate the issue again later.

**Comment by m1k3s** [comment]
I'm not sure why that would be the case, the reptile recipes are copies of the minecraft recipes with different items. I'm not sure what the issue would be here. I'm actually done with the recipe update, so I'm leaning toward closing this issue.
