### ISSUE TITLE
Reptile Hide Doesn't Have Any Recipe

### ISSUE THREAD

**Issue by kenijey** [m1k3s/reptiles#9]
please add something(recipe) that lets us use it as a leather or st like that.  thanks

**Comment by Zarepheth** [comment]
On an interim basis, even adding the leather to the Ore Dictionary so anything recipe that accepts "leather" would also accept the reptile leather (perhaps with sizing (regular/cow, small/rabbit) based upon the source reptile...)

**Comment by m1k3s** [comment]
I'm testing the idea of adding reptile hide to the ore dictionary as "leather". If it works out I'll release the update today or tomorrow.

**Comment by Zarepheth** [comment]
Thanks, that change works great! I can now make items requiring leather without hunting down some cattle - the much more prevalent reptiles do the job!

**Comment by kenijey** [comment]
Thank you so much cracked egg
